"""Type stubs for the turbo-surf PyO3 binding."""

from typing import List, Optional

class TurboSurfError(Exception):
    """A fatal turbo-surf engine fault (invalid input or a render-tier failure)."""

def version() -> str: ...
def markdown(html: str, base_url: str = ...) -> str: ...
def text(html: str) -> str: ...
def title(html: str) -> str: ...
def html(html: str) -> str: ...
def links(html: str, base_url: str = ...) -> List[str]: ...
def interactive_elements(html: str, base_url: str = ...) -> str: ...
def accessibility_tree(html: str) -> str: ...
def hydration_state(html: str) -> str: ...
def detect(html: str) -> str: ...
def query(html: str, selector: str, kind: Optional[str] = ...) -> str: ...
def extract(html: str, schema_json: str, base_url: str = ...) -> str: ...
def evaluate(html: str, script: str) -> str: ...
def render(html: str, script: str, base_url: str = ...) -> str: ...
def transform(src: str, ts: bool = ..., jsx: bool = ...) -> str: ...
